### ISSUE TITLE
Loading video links does not work in Firefox

### ISSUE THREAD

**Issue by cpiber** [cpiber/NebulaEnhance#34]
In Firefox, no video links (YouTube -> Nebula, Nebula -> YouTube) are loaded. This is because the creators cannot be loaded anymore due to CORS restrictions.

Appears to be a bug in Firefox. Tracking: https://bugzilla.mozilla.org/show_bug.cgi?id=1796977.

**Comment by aronkvh** [comment]
btw the firefox bug is marked as `Resolved: --- → INVALID` now

**Comment by cpiber** [comment]
Yes, and I implemented the fix already and it's out since a while

**Comment by aronkvh** [comment]
> Yes, and I implemented the fix already and it's out since a while

Hmm, it still doesn't work for me. The youtube link shows in Nebula, but not the other way around.

**Comment by cpiber** [comment]
Please open a new issue for that. It's not related to this.
